prepare:
  test_size: 0.2
  random_state: 42
  target_column: "target"

train:
  model_type: "logreg"
  random_state: 42

  logreg:
    C: 1.0
    max_iter: 200

  rf:
    n_estimators: 100
    max_depth: 5
